# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='api_key',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_connections',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_month_api_calls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='days_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='domain',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='free_key',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_api_calls_per_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_concurrent_connections',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_limits_last_update',
            field=models.DateTimeField(null=True),
        ),
    ]
