# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0002_auto_20160619_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='current_connections',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='current_month_api_calls',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='days_left',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='free_key',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='max_api_calls_per_month',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='max_concurrent_connections',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_limits_last_update',
        ),
    ]
