# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 18:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('domain_name', models.CharField(max_length=512, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=8)),
                ('days', models.IntegerField(default=0)),
                ('max_concurrent_users', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(default='', max_length=512, unique=True)),
                ('api_key', models.CharField(default='', max_length=512)),
                ('days_left', models.IntegerField(default=0)),
                ('max_concurrent_connections', models.IntegerField(default=0)),
                ('current_month_api_calls', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_is_active', models.BooleanField(default=True, help_text='Enables - disables the websocket service')),
                ('service_key', models.CharField(default='', help_text='A secret key to talk to websockets service', max_length=512)),
                ('max_connection', models.IntegerField(default=5000, help_text='Server limits')),
                ('free_keys', models.BooleanField(default=False)),
                ('in_beta', models.BooleanField(default=True)),
                ('max_concurrent_connections', models.IntegerField(default=100, help_text='Domain limits')),
            ],
            options={
                'verbose_name_plural': 'settings',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_clients', models.BigIntegerField(default=0, help_text='total of clients served until today')),
                ('max_concurrent_clients', models.IntegerField(default=0, help_text='max concurrent clients ever')),
                ('max_concurrent_domains', models.IntegerField(default=0, help_text='max_concurrentdomains ever')),
                ('total_messages_broadcasted', models.BigIntegerField(default=0, help_text='totalmessaged broadcasteduntil today')),
            ],
            options={
                'verbose_name_plural': 'statistics',
            },
        ),
    ]
