# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_billing_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='in_beta',
            field=models.BooleanField(default=True),
        ),
    ]
