# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_settings_in_beta'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='max_concurrent_connections',
            field=models.IntegerField(default=100),
        ),
    ]
