# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_settings_max_concurrent_connections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='user_limits_last_update',
        ),
    ]
