# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_remove_domain_user_limits_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='current_connections',
        ),
    ]
