# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_auto_20160703_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='service_key',
            field=models.CharField(default='', max_length=512),
        ),
    ]
