# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_settings_service_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='max_connection',
            field=models.IntegerField(default=5000),
        ),
    ]
