# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_auto_20160809_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_clients', models.BigIntegerField(default=0, help_text='total of clients served until today')),
                ('max_concurrent_clients', models.IntegerField(default=0, help_text='max concurrent clients ever')),
            ],
            options={
                'verbose_name_plural': 'statistics',
            },
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name_plural': 'settings'},
        ),
    ]
