# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_auto_20160809_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_clients', models.BigIntegerField(default=0)),
                ('max_concurrent_clients', models.IntegerField(default=0)),
            ],
        ),
    ]
