# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0011_stats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stats',
            options={'verbose_name_plural': 'stats'},
        ),
    ]
