# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0013_auto_20160809_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='max_concurrent_clients',
            new_name='max_clients',
        ),
    ]
